version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./.volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build: ./
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/oop
    ports:
      - "3000:3000"
    links:
      - db
    tty: true
    stdin_open: true

